### ISSUE TITLE
Значения цвета

### ISSUE THREAD

**Issue by Morfey216** [StrehaAleksandr/cat_energy#1]
Цветовые значения правильно прописывать не ключевыми словами, а в 16-ричном формате.
https://github.com/StrehaAleksandr/cat_energy/blob/ee11c1dcf12bfb57fe47c549d0570401f0159726/style.css#L28
https://github.com/StrehaAleksandr/cat_energy/blob/ee11c1dcf12bfb57fe47c549d0570401f0159726/style.css#L45

Пройтись по коду и исправить. Иначе будут ошибки по соответствию макету, наподобие этой:
http://joxi.ru/Q2KNPJYHO4Jj1m

**Comment by StrehaAleksandr** [comment]
сделал
