### ISSUE TITLE
Доступность

### ISSUE THREAD

**Issue by Morfey216** [StrehaAleksandr/cat_energy#11]
Для секций рекомендуется прописывать заголовки, которые поясняют общий смысл содержимого. Заголовки нужно прописывать даже в том случае, если они не прорисованы по дизайну в макете.
https://github.com/StrehaAleksandr/cat_energy/blob/ee11c1dcf12bfb57fe47c549d0570401f0159726/index.html#L38-L41

**Comment by StrehaAleksandr** [comment]
готово
