### ISSUE TITLE
Идентификация данных из формы

### ISSUE THREAD

**Issue by Morfey216** [StrehaAleksandr/cat_energy#13]
Каким образом сервер должен понять, откуда приходят данные?
Например здесь придут два числа, 3 и 5 - что из них вес, а что - возраст?
https://github.com/StrehaAleksandr/cat_energy/blob/ee11c1dcf12bfb57fe47c549d0570401f0159726/form.html#L41-L48
Или в этом случае - что выбрал пользователь: сахар, воду или молоко?
https://github.com/StrehaAleksandr/cat_energy/blob/ee11c1dcf12bfb57fe47c549d0570401f0159726/form.html#L90

У полей формы в обязательном порядке нужно прописывать `name`

**Comment by StrehaAleksandr** [comment]
готово
