### ISSUE TITLE
Head and title

### ISSUE THREAD

**Issue by Morfey216** [StrehaAleksandr/cat_energy#5]
В разделе head рекомендуется прописывать title с названием страницы
https://github.com/StrehaAleksandr/cat_energy/blob/ee11c1dcf12bfb57fe47c549d0570401f0159726/catalog.html#L3-L6

**Comment by StrehaAleksandr** [comment]
Сделал

**Comment by Morfey216** [comment]
Не совсем... Класс не указывается
https://github.com/StrehaAleksandr/cat_energy/blob/c6fc0017c58044c91bdea31c41437ec3c5abb34a/index.html#L6

**Comment by StrehaAleksandr** [comment]
готово
