### ISSUE TITLE
Циклическая ссылка

### ISSUE THREAD

**Issue by Morfey216** [StrehaAleksandr/cat_energy#7]
Ссылка в логотипе нужна для перехода на главную страницу. Если посетитель УЖЕ находится на главной, ссылка не должна работать, иначе вызывает циклический переход на ту же страницу.

https://github.com/StrehaAleksandr/cat_energy/blob/ee11c1dcf12bfb57fe47c549d0570401f0159726/index.html#L10-L12

Атрибут `href` нужно убрать. То же самое на главной в  логотипе футера.

Здесь та же проблема: 
https://github.com/StrehaAleksandr/cat_energy/blob/ee11c1dcf12bfb57fe47c549d0570401f0159726/index.html#L16

И здесь
https://github.com/StrehaAleksandr/cat_energy/blob/ee11c1dcf12bfb57fe47c549d0570401f0159726/catalog.html#L19

И здесь
https://github.com/StrehaAleksandr/cat_energy/blob/ee11c1dcf12bfb57fe47c549d0570401f0159726/form.html#L22
Ссылка со страницы не должна вести на саму себя. Исключения могут составлять только ссылки по якорям.

**Comment by StrehaAleksandr** [comment]
Сделал
