### ISSUE TITLE
Адресация ссылок в блоках Похудение и Набор массы

### ISSUE THREAD

**Issue by Morfey216** [StrehaAleksandr/cat_energy#9]
Согласно пункта 4.3 ТЗ ссылки должны вести на отдельные разделы каталога, а не на сам каталог.
https://github.com/StrehaAleksandr/cat_energy/blob/ee11c1dcf12bfb57fe47c549d0570401f0159726/index.html#L48
https://github.com/StrehaAleksandr/cat_energy/blob/ee11c1dcf12bfb57fe47c549d0570401f0159726/index.html#L58

**Comment by StrehaAleksandr** [comment]
Пункт 4.3 ТЗ "​В блоках «Похудение» и «Набор массы» ссылкой должна быть строка,
начинающаяся со слова «Каталог». При нажатии должен осуществляться переход
на соответствующие разделы каталога. Страницы разделов реализовывать не
нужно."
Как реализовать переход на отдельные разделы каталога, если нет страниц для этих разделов?

**Comment by StrehaAleksandr** [comment]
Можно повесить якоря, но тогда не понятно куда их вешать

**Comment by StrehaAleksandr** [comment]
Сделал

**Comment by Morfey216** [comment]
> Как реализовать переход на отдельные разделы каталога, если нет страниц для этих разделов?

Просто указывается ссылка на необходимую страницу или ресурс, который позже будет реализован, возможно даже кем-то другим.

**Comment by Morfey216** [comment]
> Сделал

Принял
